#PROGRAM TO ENTER RADIUS OF A CIRCLE AND CALCULATE AREA AND CIRCUMFERENCE OF THE CIRCLE
pi=3.14
r=float(input("ENTER A VALUE FOR RADIUS"))
print("CIRCUMFERENCE IS", 2*pi*r )
print("AREA IS", pi*r*r)
