#PROGRAM TO ENTER VALUE IN CENTIMETER AND CONVERT INTO METER AND KILOMETER.
c=float(input("ENTER A VALUE IN CENTIMETER"))
print("VALUE IN METER IS", c/100)
print("VALUE IN KILOMETER IS", c/100000)
