#PROGRAM TO ENTER BASE AND HEIGHT OF TRIANGLE AND CALCULATE AREA OF TRIANGLE.
base=int(input("ENTER THE BASE OF TRIANGLE:"))
height=int(input("ENTER THE HEIGHT OF TRIANGLE:"))
area=0.5*base*height
print("THE AREA IS:",area)
