#WRITE PYTHON PROGRAM TPO ENTER LENGTH AND BREADTH OF A RECTANGLE AND CALCULATE AREA AND PERIMETER OF THE RECTANGLE.
l=float(input("ENTER A VALUE FOR LENGTH"))
b=float(input("ENTER A VALUE FOR BREADTH"))
print("THE AREA OF THE RECTANGLE IS", l*b)
print("THE PERIMETER OF THE RECTANGLE IS", 2*(l+b))
